In [1]:
import torch

In [4]:
x=torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numel()方法返回tensor中元素的总数

In [3]:
x.numel()

10

torch.randn()是在正态分布中的随机采样

In [5]:
torch.randn(3,4)

tensor([[-0.2079, -0.0195, -0.4151, -0.8967],
        [-0.4731,  2.9884,  0.0722,  0.8519],
        [-0.4204, -0.7754, -0.3399, -0.0309]])

多个tensor连接到一起。dim=0就是按照shape中的第一个元素连接；dim=1就是按照shape中的第二个元素连接

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
X, Y, X > Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

广播机制（两维）

In [31]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

多维广播机制（没看懂）

In [37]:
a = torch.arange(6).reshape(1, 2, 3)
b = torch.arange(6).reshape(2, 1, 3)
a, b

(tensor([[[0, 1, 2],
          [3, 4, 5]]]),
 tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]))

In [38]:
a + b

tensor([[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 3,  5,  7],
         [ 6,  8, 10]]])

为多个元素赋同样的值

In [7]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

X=X+Y和X+=Y不同：第二个是原地操作

In [8]:
before = id(X)
X = X + Y
id(X) == before

False

In [9]:
before = id(X)
X += Y
id(X) == before

True

item()函数返回的是一个标量

In [10]:
a = torch.tensor([3.5])
a, a.item()

(tensor([3.5000]), 3.5)

In [41]:
torch.arange(48).reshape(2,2,3,4)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]],


        [[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]]])